pipeline updated: docer image delete

diff --git a/Jenkinsfiles b/Jenkinsfiles
--- a/Jenkinsfiles
+++ b/Jenkinsfiles
@@ -1,5 +1,5 @@
 pipeline{
-    agent any
+    agent {label 'build-vm'}
     stages{
         stage('gitclone'){
             steps{
@@ -28,5 +28,15 @@ pipeline{
         }
 
         }
+    }
+    post {
+        success{
+            echo "Build ${env.BUILD_NUMBER} succeeded - image on docker hub"
+            sh 'docker rmi jyotimanab/helloapp:${BUILD_NUMBER} || echo "Cleanup: image not found locally"'
+        }
+        failure{
+            echo "Pipeline Failed - image kept locally for debugging"
+        }
+        
     }
 }
